version: '2.0'
services:
  
  sonarqube:
    build: ./build-sonarqube
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - "./volumes/sonarqube/data:/opt/sonarqube/data"
      - "./volumes/sonarqube/extensions:/opt/sonarqube/extensions"
    depends_on:
      - db

  db:
    image: postgres
    container_name: db_sonarqube
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    # Da erro na VM do OSX
    volumes:
     - "./volumes/postgresql/data:/var/lib/postgresql/data"

  jenkins-portais:
    build: ./build-jenkins
    container_name: portais
    user: root
    ports:
      - "9080:8080"
    volumes:
      - "./volumes/jenkins/portal:/var/jenkins_home"
    depends_on:
      - sonarqube
    links:
      - sonarqube

  nginx:
    build: ./build-nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - sonarqube
      - jenkins-portais
    links:
      - sonarqube
      - jenkins-portais